Fix BATCH execution error (#351)
Added tests for BATCH execution in cloud

This was causing a pickling error during BATCH execution. 

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/tdbudf/batch_udf_main.py", line 339, in real_main
    result = udf(*args, **kwargs)
  File "/Users/npapa/miniforge3/envs/tiledb_vs_8_arm/lib/python3.9/site-packages/tiledb/vector_search/object_api/embeddings_ingestion.py", line 432, in ingest_embeddings
  File "/opt/conda/lib/python3.9/site-packages/tiledb/cloud/dag/dag.py", line 1162, in compute
    self._batch_taskgraph = self._build_batch_taskgraph()
  File "/opt/conda/lib/python3.9/site-packages/tiledb/cloud/dag/dag.py", line 1534, in _build_batch_taskgraph
    kwargs["executable_code"] = codecs.PickleCodec.encode_base64(func)
  File "/opt/conda/lib/python3.9/site-packages/tiledb/cloud/_results/codecs.py", line 54, in encode_base64
    data_bytes = cls.encode(obj)
  File "/opt/conda/lib/python3.9/site-packages/tiledb/cloud/_results/codecs.py", line 151, in encode
    return cloudpickle.dumps(obj, protocol=_PICKLE_PROTOCOL)
  File "/opt/conda/lib/python3.9/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/opt/conda/lib/python3.9/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'FilterList' object
```